GPU: '0'
b1: 0.5
b2: 0.999
batch_size: 1
datasets_path: datasets//dongyufan3
fmap: 16
gap_t: 9
gap_x: 76
gap_y: 76
lr: 5.0e-05
n_epochs: 100
output_dir: ./results
overlap_factor: 0.4
patch_t: 16
patch_x: 128
patch_y: 128
pth_path: ./pth/dongyufan3_202312251537
scale_factor: 1
select_img_num: 100000
train_datasets_size: 5000
